# Generated by Django 3.1.7 on 2021-03-03 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='student',
            new_name='students',
        ),
    ]
